name: Converter para WebP
on:
  push:
    branches:
      - main
    paths:
      - 'img/**' # Só dispara se houver mudanças na pasta img

jobs:
  convert_images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô gravar as imagens no teu repo

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Suporte AVIF (ImageMagick)
        run: sudo apt-get update && sudo apt-get install -y imagemagick libheif-examples

      - name: Criar pasta webp se não existir
        run: mkdir -p img/webp

      - name: Converter Imagens (PNG, JPG, AVIF -> WebP)
        run: |
          # Procura ficheiros na pasta img (sem entrar na subpasta webp)
          # Converte cada um para .webp dentro da pasta img/webp/
          find img/ -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.avif" -o -iname "*.jpeg" \) -exec sh -c '
            filename=$(basename "$1")
            extension="${filename##*.}"
            basename="${filename%.*}"
            echo "A converter: $filename para $basename.webp"
            convert "$1" "img/webp/${basename}.webp"
          ' _ {} \;

      - name: Guardar Alterações no GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-conversão de imagens para WebP [skip ci]"
          file_pattern: 'img/webp/*.webp'
